name : Communicating with Cliq

on:
  push:
  workflow_dispatch:
jobs:
  test_name:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - run: echo "Hello 1"
      - run: echo "Hello 2"
      - run: echo "Hello 3"
      - run: echo "Hello 4"
      - run: echo "Hello 5"
